site_name: AthenaX Documentation
edit_uri: edit/master/docs/
theme_dir: docs/theme
markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
site_favicon: 'images/favicon.ico'
repo_name: 'uber/AthenaX'
repo_url: 'https://github.com/uber/AthenaX'
extra:
  logo: 'images/athena-logo.png'
google_analytics:
  - 'UA-3196917-8'
  - 'auto'
pages:
  - 'Introduction': 'index.md'
  - 'Getting Started' : 'getting_started.md'
  - 'Design' : 'design.md'
  - 'Examples' : 'examples.md'
